name: Node.js Workflow

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: dev # Your environment with the MongoDB secret

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Update to a newer version that supports '??='

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: |
          node index.js
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }} # Your MongoDB connection string secret
